export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SET_PATH = "SET_PATH";

export const LOGOUT = "LOGOUT";
export const CREATE_WORK_SUCCESS = "CREATE_WORK_SUCCESS";
export const CREATE_WORK_START = "CREATE_WORK_START";
export const CREATE_WORK_FAIL = "CREATE_WORK_FAIL";
export const UPLOAD_WORKS_START = "UPLOAD_WORKS_START";
export const UPLOAD_WORKS_SUCCESS = "UPLOAD_WORKS_SUCCESS";
export const UPLOAD_WORKS_FAIL = "UPLOAD_WORKS_FAIL";
//
//
export const REMOVE_WORK_START = "REMOVE_WORK_START";
export const REMOVE_WORK_FAIL = "REMOVE_WORK_FAIL";
export const REMOVE_WORK_SUCCESS = "REMOVE_WORK_SUCCESS";
//
//
export const SET_REDIRECT_WORK_PATH = "SET_REDIRECT_WORK_PATH";
export const GET_JOB_START = "GET_JOB_START";
export const GET_JOB_FAIL = "GET_JOB_FAIL";
export const GET_JOB_SUCCESS = "GET_JOB_SUCCESS";
//
//
//
export const LEAVE_WORK_START = "LEAVE_WORK_START";
export const LEAVE_WORK_FAIL = "LEAVE_WORK_FAIL";
export const LEAVE_WORK_SUCCESS = "LEAVE_WORK_SUCCESS";
